apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0f58cb145fa077b5b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static-claim
spec:
  storageClassName:
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata: 
  name: ebs-static-pod
spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts: 
    - name: ebs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-static
    persistentVolumeClaim:
      claimName: ebs-static-claim 